force-app/main/default/objects/Board_Audio__c/Board_Audio__c.object-meta.xml
<CustomObject>
    <label>Board Audio</label>
    <nameField>
        <label>Board Sound Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Audios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Audio__c/fields/Sound__c.field-meta.xml
<CustomField>
    <fullName>Sound__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sound</label>
    <referenceTo>Sound__c</referenceTo>
    <relationshipLabel>Board Audios</relationshipLabel>
    <relationshipName>Board_Audios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Board_Audio__c/fields/Soundboard__c.field-meta.xml
<CustomField>
    <fullName>Soundboard__c</fullName>
    <label>Soundboard</label>
    <referenceTo>Soundboard__c</referenceTo>
    <relationshipLabel>Board Audios</relationshipLabel>
    <relationshipName>Board_Audios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sound__c/Sound__c.object-meta.xml
<CustomObject>
    <label>Sound</label>
    <nameField>
        <label>Sound Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sound__c/fields/Audio_IMG__c.field-meta.xml
<CustomField>
    <fullName>Audio_IMG__c</fullName>
    <label>Audio IMG</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sound__c/fields/Audio_Src__c.field-meta.xml
<CustomField>
    <fullName>Audio_Src__c</fullName>
    <description>https://ddo000001c7kima0-dev-ed--c.develop.vf.force.com/resource/1682633351000/audio</description>
    <formula>IF(audioUpload__c = TRUE, &quot;/resource/1682633351000/audio&quot;, &quot;/resource/1682633351000/audio&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Audio_Src</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sound__c/fields/Audio_URL__c.field-meta.xml
<CustomField>
    <fullName>Audio_URL__c</fullName>
    <label>Audio URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Soundboard__c/Soundboard__c.object-meta.xml
<CustomObject>
    <label>Soundboard</label>
    <nameField>
        <displayFormat>SB-{0000}</displayFormat>
        <label>Soundboard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soundboards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SoundController.cls
public with sharing class SoundController {
    
    @AuraEnabled(cacheable=true)
    public static List<Sound__c> getSoundList(String searchKey) {
        String searchString = '%' + searchKey + '%';
        return [SELECT Id, Name, Audio_Src__c, Audio_IMG__c from Sound__c  Where Name Like :searchString Limit 5];
    }
    
    @AuraEnabled
    public static Sound__c createSound(String name, String audioDocumentId, String imageDocumentId, String soundboardId) { 
        ContentVersion audioFileId = returnFileId(audioDocumentId);
        ContentVersion imageFileId = returnFileId(imageDocumentId);

        String audioPublicUrl = createContentDistribution(name, audioFileId.id);
        String imagePublicUrl = createContentDistribution(name, imageFileId.id);

        Sound__c newSound = new Sound__c(
            Audio_IMG__c = imagePublicUrl,
            Audio_URL__c = audioPublicUrl,
            Name = name
        );
        insert newSound;

        Board_Audio__c newBoardAudio = new Board_Audio__c(
            Soundboard__c = soundboardId,
            Sound__c = newSound.Id,
            Name = newSound.Name
        );
        insert newBoardAudio;

        return newSound;  
    }

    private static ContentVersion returnFileId(String docId) {
        return [Select Id, Title From ContentVersion Where ContentDocumentId = :docId];
    }

    private static String createContentDistribution(String Title, String id) {
        ContentDistribution newContent = new ContentDistribution(Name = Title, ContentVersionId = id,
        PreferencesAllowViewInBrowser = true);
        insert newContent;
        ContentDistribution publicUrl = [Select DistributionPublicUrl from ContentDistribution Where id = :newContent.Id];
        return publicUrl.DistributionPublicUrl;
    }
}