force-app/main/default/objects/Board_Audio__c/Board_Audio__c.object-meta.xml
<CustomObject>
    <label>Board Audio</label>
    <nameField>
        <label>Board Sound Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Audios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Audio__c/fields/Sound__c.field-meta.xml
<CustomField>
    <fullName>Sound__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sound</label>
    <referenceTo>Sound__c</referenceTo>
    <relationshipLabel>Board Audios</relationshipLabel>
    <relationshipName>Board_Audios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Board_Audio__c/fields/Soundboard__c.field-meta.xml
<CustomField>
    <fullName>Soundboard__c</fullName>
    <label>Soundboard</label>
    <referenceTo>Soundboard__c</referenceTo>
    <relationshipLabel>Board Audios</relationshipLabel>
    <relationshipName>Board_Audios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sound__c/Sound__c.object-meta.xml
<CustomObject>
    <label>Sound</label>
    <nameField>
        <label>Sound Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sound__c/fields/Audio_IMG__c.field-meta.xml
<CustomField>
    <fullName>Audio_IMG__c</fullName>
    <label>Audio IMG</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sound__c/fields/Audio_Src__c.field-meta.xml
<CustomField>
    <fullName>Audio_Src__c</fullName>
    <description>https://ddo000001c7kima0-dev-ed--c.develop.vf.force.com/resource/1682633351000/audio</description>
    <formula>IF(audioUpload__c = TRUE, &quot;/resource/1682633351000/audio&quot;, &quot;/resource/1682633351000/audio&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Audio_Src</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sound__c/fields/Audio_URL__c.field-meta.xml
<CustomField>
    <fullName>Audio_URL__c</fullName>
    <label>Audio URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Soundboard__c/Soundboard__c.object-meta.xml
<CustomObject>
    <label>Soundboard</label>
    <nameField>
        <displayFormat>SB-{0000}</displayFormat>
        <label>Soundboard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soundboards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BoardAudioController.cls
public without sharing class BoardAudioController {
    @AuraEnabled(cacheable=true)
    public static List<Board_Audio__c> getBoardAudio(String soundboardId) {
        String searchString = '%' + soundboardId + '%';
        try {
            return [SELECT Id, Sound__r.Name, Sound__r.Audio_Src__c, Sound__r.Audio_URL__c, Sound__r.Audio_IMG__c from Board_Audio__c  Where Soundboard__c = :soundboardId];
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }  
    }
}